DOCGroup/XSC

XSC/be/CXX/Inline.cpp
XSC/be/CXX/WriterSource.cpp

* XSC/be/CXX/WriterSource.cpp:

Use std::addressof()

---

XSC/be/CXX/Elements.cpp
XSC/be/CXX/Inline.cpp
XSC/be/CXX/WriterHeader.cpp
XSC/be/CXX/WriterSource.cpp

* XSC/be/CXX/Elements.cpp:
* XSC/be/CXX/WriterHeader.cpp:
* XSC/be/CXX/WriterSource.cpp:

Simplifications to the generated code

---

.gitmodules

Removed file, we are not using submodules

---

contrib/CCF/CCF/Bootstrap.rules
contrib/CCF/CCF/Config.rules

* contrib/CCF/CCF/Bootstrap.rules:
* contrib/CCF/CCF/Config.rules:

Remove old Id tags

---

README.md
XSC/be/CXX/Elements.hpp
XSC/be/CXX/Header.cpp
XSC/be/CXX/Inline.cpp
XSC/be/IDL/Elements.hpp
XSCRT/XMLSchema/id_map.hpp

Added codacy badge, more dense code generation, added explicit to single argument constructors

---

XSC/be/CXX/WriterSource.cpp

* XSC/be/CXX/WriterSource.cpp:

Fixed error in non C++11 case

---

XSC/be/CXX/Source.cpp
XSC/be/CXX/TraversalSource.cpp
XSC/be/CXX/WriterHeader.cpp

* XSC/be/CXX/Source.cpp:
* XSC/be/CXX/TraversalSource.cpp:
* XSC/be/CXX/WriterHeader.cpp:

Fixed codacy issues

---

XSC/be/CXX/Inline.cpp
XSC/be/CXX/ParserSource.cpp
XSC/be/CXX/Source.cpp
XSC/be/CXX/WriterSource.cpp

* XSC/be/CXX/ParserSource.cpp:
* XSC/be/CXX/Source.cpp:
* XSC/be/CXX/WriterSource.cpp:

Fixes to the generated code when using char instead of ACE_TCHAR

---

XSC/be/CXX/Elements.hpp
XSC/be/CXX/Header.cpp
XSC/be/CXX/Inline.cpp
XSC/be/CXX/Source.cpp
XSCRT/XSCRT/Elements.hpp

* XSC/be/CXX/Elements.hpp:
* XSC/be/CXX/Header.cpp:
* XSC/be/CXX/Source.cpp:
* XSCRT/XSCRT/Elements.hpp:

Use string_type and std::string in case of ascii

---

XSC/be/CXX/Header.cpp
XSC/be/CXX/Inline.cpp

With C++11 there is no need for non-const iterators

---

XSC/be/CXX/Inline.cpp

Simplified get_idref calls

---

TODO
azure-pipelines.yml

Update to trigger azure

---

azure-pipelines.yml

…pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md the azure ubuntu image does have boost
* azure-pipelines.yml:

Download and compile our own version of boost as part of the XSC azure CI

---

azure-pipelines.yml

Added schedule to build each Sunday

---

.travis.yml

Use ubuntu bionic release on travis

---

.travis.yml
azure-pipelines.yml

Use ubuntu 18.04 with system boost and gcc8

---

XSC/be/CXX/Header.cpp

Removed redundant whitespace

---

XSC/be/CXX/Inline.cpp

Removed redundant void for count operation

---

MPC/config/xsc_base.mpb

Put XSC variables in project through verbatim

---

.github/workflows/linux.yml

* .github/workflows/linux.yml:

Limit access for github actions

---

XSC/be/CXX/Header.cpp
XSC/be/CXX/Inline.cpp

Add del operations for sequences

---

XSC/be/CXX/Generator.cpp

Add support for include guard on the commandline

---

XSC/be/CXX/Elements.cpp
XSC/be/CXX/Header.cpp
XSC/be/CXX/Inline.cpp
XSC/be/CXX/Source.cpp
XSCRT/XSCRT/Elements.hpp

Removed redundant whitespaces
